// one bowl list, used by the menu and the home preview
export const BOWLS = [
  {
    name: "Basic Bitch",
    body: "Banana, blueberries, kiwi, goji berries, cacao nibs.",
    tag: "Crowd favourite",
    emoji: "🫐",
    accent: "#EC4899",
    tintA: "#FFE7F4",
    tintB: "#FFD3EC",
    bowlA: "#FB7DC0",
    bowlB: "#A81368",
  },
  {
    name: "The Crunch Situation",
    body: "Lotus crumbs, Oreo crumbs, sunflower & pumpkin seeds, cacao nibs.",
    tag: "For the texture people",
    emoji: "🍪",
    accent: "#7C3AED",
    tintA: "#EFE7FE",
    tintB: "#E0D2FC",
    bowlA: "#A78BFA",
    bowlB: "#4C1D95",
  },
  {
    name: "Fruitationship",
    body: "Dragon fruit, kiwi, blueberries, banana, goji berries.",
    tag: "All fruit, no drama",
    emoji: "🥝",
    accent: "#22A06B",
    tintA: "#E4F7EC",
    tintB: "#CFF0DE",
    bowlA: "#5CD69B",
    bowlB: "#166E4C",
  },
  {
    name: "My Ideal Type",
    body: "Your bowl, your rules — pick any four toppings.",
    tag: "Build your own",
    emoji: "✨",
    accent: "#F0910A",
    tintA: "#FFF0DA",
    tintB: "#FFE1B5",
    bowlA: "#FFC163",
    bowlB: "#B4600A",
  },
];
