// one bowl list, used by the menu and the home line-up
export const BOWLS = [
  {
    n: "01",
    name: "Basic Bitch",
    body: "Banana, blueberries, kiwi, goji berries, cacao nibs.",
    tag: "Crowd favourite",
    accent: "#C0246B",
    tintA: "#F6EDF2",
    tintB: "#EDDDE7",
    bowlA: "#E0699F",
    bowlB: "#6E1B46",
  },
  {
    n: "02",
    name: "The Crunch Situation",
    body: "Lotus crumbs, Oreo crumbs, sunflower & pumpkin seeds, cacao nibs.",
    tag: "For the texture people",
    accent: "#5B2BAE",
    tintA: "#F1EDF7",
    tintB: "#E3DAEF",
    bowlA: "#9B7BD4",
    bowlB: "#34195C",
  },
  {
    n: "03",
    name: "Fruitationship",
    body: "Dragon fruit, kiwi, blueberries, banana, goji berries.",
    tag: "All fruit, no drama",
    accent: "#8F2794",
    tintA: "#F4EDF6",
    tintB: "#E9D9EE",
    bowlA: "#BE6EC9",
    bowlB: "#4A1153",
  },
  {
    n: "04",
    name: "My Ideal Type",
    body: "Your bowl, your rules — pick any four toppings.",
    tag: "Build your own",
    accent: "#A9662A",
    tintA: "#F7F2EA",
    tintB: "#EDE2D3",
    bowlA: "#E0A45C",
    bowlB: "#6E3D12",
  },
];
